Prevent (hidden) runtime exception
rokucommunity/vscode-brightscript-language pull request #286
Opened 2020-12-04 19:34 UTC by elsassph

Extensions would internally silently crash when `roku-debug` sends a message with a text body instead of an array of errors.

2020-12-09 20:19 UTC, TwitchBronBron requested changes

2020-12-09 20:19 UTC, TwitchBronBron commented on src/LogOutputManager.ts
> +        const method = fsPath && this.declarationProvider.getFunctionBeforeLine(fsPath, lineNumber);
This boolean-ish logic doesn't make much sense to me with respect to what is happening here. Do you think you could refactor it a little bit (perhaps an `if` statement) to make it more clear what role `fsPath` has to play in computing `method`.

2020-12-10 09:24 UTC, elsassph commented on src/LogOutputManager.ts
> +            e.body.forEach(async (compileError: { path?: string }) => {
I don't know haha, that was async.

2020-12-10 09:48 UTC, elsassph commented on src/LogOutputManager.ts
> +            e.body.forEach(async (compileError: { path?: string }) => {
This codebase is full of `forEach` and I think it would be a bit gratuitous to start refactoring them to `for of`.

2020-12-10 12:11 UTC, merged